#ifndef JPEG_H
#define JPEG_H

#include <stdbool.h>
#include <error.h>
#include <stdlib.h>

typedef unsigned char byte;
typedef unsigned int uint;

#define QUANTIZATION_TABLE_SZ 64
#define MAX_QUANTIZATION_TABLES 4
#define MAX_HUFFMAN_TABLES 4

// hold DCT coefficients for y, cb, and cr channels
typedef struct Block Block;
struct Block {
    int y[64];   // Luminance Y or Red R channel
    int cb[64];  // Blue chrominance Cb or Green G channel
    int cr[64];  // Red chrominance Cr or Blue B channel
};

// Symbols are 8 bit values for (run, length) pairs, recall that run is the number of zeros that preceeds the code, and length is the bit length of the code.
typedef struct Huffman_Table Huffman_Table;
struct Huffman_Table {
    byte offsets[17]; // Huffman codes are 1-16bits long, offsets stores the cumulative number symbols with codes of length <= i bits
    byte symbols[162]; // JPEG specification says generally up to 162 symbols/codes per table 
    uint codes[162]; // TODO make these hardcoded numbers definitions
    bool is_set;
};

typedef struct Quantization_Table Quantization_Table;
struct Quantization_Table {
    uint table[QUANTIZATION_TABLE_SZ];
    bool valid;
};

typedef struct Color_Component Color_Component;
struct Color_Component {
    byte hor_sampling_factor;
    byte ver_sampling_factor;
    byte quantization_table_id;
    byte huffman_dc_table_id;
    byte huffman_ac_table_id;
    bool used_in_frame;
    bool used_in_scan;
};

// minimum coded unit of compressed data
typedef struct MCU MCU;
struct MCU {
    // * union since decoding needs original rgb, encoding needs ycbcr
    union {
        int y[64];
        int r[64];
    };
    union {
        int cb[64];
        int g[64];
    };
    union {
        int cr[64];
        int b[64];
    };
};

typedef struct Image Image;
struct Image {
    bool valid;
    bool is_progressive; // either baseline or progressive jpeg
    uint height;
    uint width;
    byte num_components; // either 1 for grayscale, or 3 for rgb/ycbcr
    bool zero_based; 

    // SOS marker info
    // TODO mostly progressive stuff
    byte components_in_scan;
    byte start_of_selection;
    byte end_of_selection;
    byte successive_approx_high;
    byte successive_approx_low;

    // Block dimensions
    uint block_height;
    uint block_width;
    uint block_height_real;
    uint block_width_real;

    // MCU data
    Block* blocks;  // Array of blocks of pixel data

    byte horizontal_sampling_factor;
    byte vertical_sampling_factor;

    // DRI marker
    uint restart_interval;

    Color_Component color_components[3];
    Quantization_Table quantization_tables [MAX_QUANTIZATION_TABLES];
    Huffman_Table huffman_dc_tables[MAX_HUFFMAN_TABLES]; // id can be between 0 and 3 for each table
    Huffman_Table huffman_ac_tables[MAX_HUFFMAN_TABLES];
};

// * markers and array maps generated by chatgpt
static const byte zig_zag_map[] = { // for decoding jpeg quantization tables
    0,   1,  8, 16,  9,  2,  3, 10,
    17, 24, 32, 25, 18, 11,  4,  5,
    12, 19, 26, 33, 40, 48, 41, 34,
    27, 20, 13,  6,  7, 14, 21, 28,
    35, 42, 49, 56, 57, 50, 43, 36,
    29, 22, 15, 23, 30, 37, 44, 51,
    58, 59, 52, 45, 38, 31, 39, 46,
    53, 60, 61, 54, 47, 55, 62, 63
};

// Start of Frame markers, non-differential, Huffman coding
#define SOF0  0xC0  // Baseline 
#define SOF1  0xC1  // Extended sequential DCT - NOT USED
#define SOF2  0xC2  // Progressive DCT
#define SOF3  0xC3  // Lossless (sequential) - NOT USED

// Start of Frame markers, differential, Huffman coding
#define SOF5  0xC5  // Differential sequential DCT
#define SOF6  0xC6  // Differential progressive DCT
#define SOF7  0xC7  // Differential lossless (sequential)

// Start of Frame markers, non-differential, arithmetic coding
#define SOF9  0xC9  // Extended sequential DCT
#define SOF10 0xCA  // Progressive DCT
#define SOF11 0xCB  // Lossless (sequential)

// Start of Frame markers, differential, arithmetic coding
#define SOF13 0xCD  // Differential sequential DCT
#define SOF14 0xCE  // Differential progressive DCT
#define SOF15 0xCF  // Differential lossless (sequential)

// Define Huffman Table(s)
#define DHT 0xC4

// JPEG extensions
#define JPG 0xC8

// Define Arithmetic Coding Conditioning(s)
#define DAC 0xCC

// Restart interval Markers
#define RST0 0xD0
#define RST1 0xD1
#define RST2 0xD2
#define RST3 0xD3
#define RST4 0xD4
#define RST5 0xD5
#define RST6 0xD6
#define RST7 0xD7

// Other Markers
#define SOI 0xD8  // Start of Image
#define EOI 0xD9  // End of Image
#define SOS 0xDA  // Start of Scan
#define DQT 0xDB  // Define Quantization Table(s)
#define DNL 0xDC  // Define Number of Lines
#define DRI 0xDD  // Define Restart Interval
#define DHP 0xDE  // Define Hierarchical Progression
#define EXP 0xDF  // Expand Reference Component(s)

// APPN Markers, not used
#define APP0  0xE0
#define APP1  0xE1
#define APP2  0xE2
#define APP3  0xE3
#define APP4  0xE4
#define APP5  0xE5
#define APP6  0xE6
#define APP7  0xE7
#define APP8  0xE8
#define APP9  0xE9
#define APP10 0xEA
#define APP11 0xEB
#define APP12 0xEC
#define APP13 0xED
#define APP14 0xEE
#define APP15 0xEF

// Misc Markers, not used
#define JPG0  0xF0
#define JPG1  0xF1
#define JPG2  0xF2
#define JPG3  0xF3
#define JPG4  0xF4
#define JPG5  0xF5
#define JPG6  0xF6
#define JPG7  0xF7
#define JPG8  0xF8
#define JPG9  0xF9
#define JPG10 0xFA
#define JPG11 0xFB
#define JPG12 0xFC
#define JPG13 0xFD
#define COM   0xFE
#define TEM   0x01

#endif